set_hybrid_cont_calcs implemented cargo tests pass python err: TypeError: RustVehicle.__new__() missing 1 required positional argument: `input_kw_out_array`